journey
    title Twine User Journey
    section Register
      Provide name, age, location, gender: 5 : User A
      login: 5: User A
    section Login
      Login to app: 1: User A, Friend A
      Sit down: 5: Me
    section Browse Profiles
      Select profile: 5: Friend A
      Look through profile: 5: Friend A
      Make recommendation to User A: 5: Friend A
    section Profile Recommended
      Login to app: 5: Friend B
      See new recommendations: 5: Friend B
